### ISSUE TITLE
Lag between sprite events based on RPG Example

### ISSUE THREAD

**Issue by GotAnySnacks** [wise9/enchant.js#296]
The RPG Example program that's included with the enchant.js framework shows an effective way to scroll a map based on the position of a single sprite.

However, when other sprites are added to the group containing the player and the map, there is a noticable frame of lag between the player and these other sprites that causes them to be off-position as long as the screen is scrolling. This can be seen in the following projects as an example:

http://9leap.net/games/4339
http://9leap.net/games/3375
http://9leap.net/games/4294

**Comment by illfang** [comment]
Great. Thank you for confirming the fix. I'll close the issue for now. If you experience any problems please open a new ticket!
