### ISSUE TITLE
Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode'.

### ISSUE THREAD

**Issue by stpettersens** [wise9/enchant.js#312]
When I use:

```js
game.assets['sounds/hit.ogg'].play()
```

The first time this is called the sound plays fine. However if I call it again, this error is thrown:

**Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.**

I am using enchant.js 0.8.2 and testing in Chrome and serving the page with XAMPP. Works fine in Firefox, so I suspect this an issue with how enchant works with WebKit based browsers.

Thanks.

**Comment by rtsan** [comment]
Thank you for your PR
